print ("############################## ")
print ("#                            # ")
print ("#     Naila Atresia Rahma    # ")
print ("#        2510817120014       # ")
print ("#                            # ")
print ("##############################")